### ISSUE TITLE
Could not find a required package in 'build-packages': gcc-x86_64-linux-gnu

### ISSUE THREAD

**Issue by xypron** [IsaacJT/sipeed-lichee-gadget-snap#1]
Building locally on x86_64 fails with "Could not find a required package in 'build-packages': gcc-x86_64-linux-gnu".

I guess `${SNAPCRAFT_ARCH_TRIPLET}` should be replaced by `riscv64-linux-gnu` in snapcraft.yaml.

**Comment by IsaacJT** [comment]
What command are you using to build the snap? It sounds like you're missing `--target-arch=riscv64`

**Comment by xypron** [comment]
I just typed "snapcraft". As RISC-V is the only target there should be no need to add a --target-arch parameter?

**Comment by IsaacJT** [comment]
That's only the case on core22 base snaps; on core20 you have to specify `--target-arch`

**Comment by IsaacJT** [comment]
GCC packages are no longer required on Core 22 as everything is precompiled in packages
